# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [2]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [3]:
!pip -V numpy

pip 20.2.3 from c:\users\gruel\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)



#### Q3 : Créer un vecteur nul de taille 10

In [15]:
v = np.zeros((10,10)); v

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [16]:
v[3] = 1; v

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [53]:

vecZ = np.arange(10,50)
vecZ

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [54]:
vecZ.reshape(4,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [57]:
vecZ[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [61]:
mat = np.array([[1,0,4],[2,8,6],[3,5,7]]); mat

array([[1, 0, 4],
       [2, 8, 6],
       [3, 5, 7]])

#### Q8 : Créer une matrice identié 3x3 

In [63]:
matIdentite = np.array([[0,0,1],[0,1,0],[1,0,0]]); matIdentite

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [4]:
matCube = (np.random.rand(3,3,3))*10 ; matCube

array([[[3.40851154, 9.59050309, 1.71737051],
        [6.2925653 , 0.24930453, 1.02765935],
        [7.77089787, 6.33296106, 2.29466734]],

       [[6.78177326, 5.06320331, 9.31284676],
        [8.56052538, 7.62775511, 8.22059322],
        [4.89050297, 6.14588455, 6.98809009]],

       [[7.20649022, 2.74985074, 6.3151556 ],
        [0.25560681, 1.15641347, 2.52820765],
        [1.48602973, 1.86247046, 9.44846696]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [9]:
matDix = (np.random.rand(8,8))*10 ; matDix


array([[1.76684214, 2.27777734, 7.87718392, 1.35768592, 6.91035265,
        2.87915217, 7.04419152, 7.45125488],
       [1.81888148, 6.86265742, 0.10675126, 0.21252606, 6.43245404,
        3.65509069, 9.0089657 , 9.05363068],
       [5.61620795, 9.93624927, 9.38713545, 5.27936401, 9.56106185,
        8.44057008, 4.01273465, 6.48564021],
       [7.3649085 , 6.42405843, 9.93142599, 1.10045695, 6.68053804,
        1.23964119, 6.72760578, 4.86992362],
       [0.15107294, 2.81072899, 0.41299655, 3.53014457, 2.43211763,
        7.56181711, 9.8551361 , 5.53770818],
       [1.81363947, 5.59622027, 8.04289434, 4.4879673 , 8.30810694,
        8.9081022 , 5.6642813 , 3.45531155],
       [5.97226138, 1.76149132, 0.38836506, 7.6764606 , 7.60335752,
        5.558976  , 8.183157  , 3.79239694],
       [4.79775236, 0.5665975 , 3.99397359, 5.4844867 , 8.22956352,
        1.29355116, 3.21777587, 5.89042284]])

In [10]:
matDix.min()


0.10675125831454024

In [11]:
matDix.max()

9.936249266938507

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [18]:
matCinq = (np.random.rand(5,5))*10

In [19]:
matCinq[1][0]= 1
matCinq[2][1]= 2
matCinq[3][2]= 3
matCinq[4][3]= 4; matCinq

array([[7.26828872, 9.52608659, 3.12844931, 7.65572486, 7.74028179],
       [1.        , 9.59547141, 4.44285982, 9.10927685, 1.30648675],
       [6.45996645, 2.        , 3.77614059, 8.84269417, 6.88723265],
       [6.4606045 , 7.92980588, 3.        , 5.08170935, 0.29189963],
       [7.36791974, 2.82260934, 7.77794973, 4.        , 3.79629725]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [12]:
listRandom = (np.random.rand(5))*10 ; listRandom

array([3.67524029, 9.52959591, 1.32915351, 6.64612328, 9.52645758])

In [14]:
listRandom.sum()

30.706570579105865

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [24]:
listRandom = (np.random.rand(5))*10
moyenne = 0
for i, element in enumerate(listRandom) : 
    moyenne += element
moyenne = moyenne % i
moyenne

1.9209851059647143

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [63]:
def taille(listt : list):
    for i, element in enumerate(listt) :
        element += element
    return i+1 

In [64]:
l = [x for x in range(10)]
print(l)
print(taille(l))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
10


#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [66]:
listRandom = (np.random.rand(10))
listRandom

array([0.22898231, 0.80830735, 0.59327346, 0.77695545, 0.99539393,
       0.50964037, 0.44918349, 0.64439305, 0.60497582, 0.91977343])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)