In [1]:
import pandas as pd
import numpy as np

In [ ]:
chemin = "http://bit.ly/missing-values"
data = pd.read_csv(chemin)

In [2]:
data.head(10)

color  rating
0     NaN    1.16
1     Red     NaN
2    Blue    2.54
3     Red    1.51
4     Red     NaN
5    Blue     NaN
6     NaN    4.25
7    Blue     NaN
8     NaN    1.75
9  Orange    3.21

### Somme des valeurs null par colonne

In [3]:
data.isna().sum()

color     129
rating    256
dtype: int64

### Pourcentage des valeurs null par colonne


In [5]:
data.isna().mean()

color     0.140676
rating    0.279171
dtype: float64

In [6]:
data.isna()

color  rating
0     True   False
1    False    True
2    False   False
3    False   False
4    False    True
..     ...     ...
912  False   False
913  False    True
914   True   False
915  False   False
916  False    True

[917 rows x 2 columns]

### Créer la colonne qui rensigne l'absence de valeur 


In [8]:
data['color_missing'] = data['color'].isna()

In [9]:
data.head()

color  rating  color_missing
0   NaN    1.16           True
1   Red     NaN          False
2  Blue    2.54          False
3   Red    1.51          False
4   Red     NaN          False

In [10]:
data.insert(0, "color_missing2", data['color'].isna())

In [12]:
data.head()

color_missing2 color  rating  color_missing
0            True   NaN    1.16           True
1           False   Red     NaN          False
2           False  Blue    2.54          False
3           False   Red    1.51          False
4           False   Red     NaN          False

inserer une colonne pour renseigner la presence de vameur manqueante [numerique/ordinal

In [22]:
#n'inclure que le nom des colonnes numeriques/ORDINAL
for nomColonnes in ['color','rating']:
    indexColonnes = data.columns.get_loc(nomColonnes)
    data.insert(indexColonnes+1,
        nomColonnes+'_nan',
        data[nomColonnes].isna().astype('int8'))

la touhe final our les colonnes ordinales, colonne.cat.codes
pout les colonnes numeriques, as_type("int") ou as_type("float")


In [23]:
data.head(5)

color_missing2 color  color_nan  rating  rating_nan  color_missing
0            True   NaN          1    1.16           0           True
1           False   Red          0     NaN           1          False
2           False  Blue          0    2.54           0          False
3           False   Red          0    1.51           0          False
4           False   Red          0     NaN           1          False

In [28]:
chemin = "http://bit.ly/missing-values-toy"
data = pd.read_csv(chemin)

In [25]:
data.head()

Colonne Importante  Colonne Inutile  Colonne Peu Utile
0                Oui              NaN                2.0
1                Non              1.0                NaN
2         Légerement              NaN                3.0
3                NaN              1.0                NaN
4                Oui              1.0                4.0

suppresion de toute les lignes sauf 1 

In [26]:
data.dropna()

Colonne Importante  Colonne Inutile  Colonne Peu Utile
4                Oui              1.0                4.0

In [29]:
data.dropna(how="any",subset=['Colonne Importante'] )

Colonne Importante  Colonne Inutile  Colonne Peu Utile
0                Oui              NaN                2.0
1                Non              1.0                NaN
2         Légerement              NaN                3.0
4                Oui              1.0                4.0

In [46]:
url = "https://bit.ly/tx-data"
data = pd.read_csv(url)

In [40]:
data.duplicated(keep="first")

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19     True
20     True
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28     True
29    False
30    False
31    False
32     True
33    False
34    False
35    False
36    False
37     True
38    False
39    False
40    False
41    False
42     True
43    False
44    False
45    False
46    False
47    False
dtype: bool

In [41]:
import numpy as np 
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [42]:
mask = np.array([False,False,True,False,True])
x[mask]

array([3, 5])

In [43]:
x %2

array([1, 0, 1, 0, 1], dtype=int32)

In [56]:
duplication = data.duplicated(keep=False, subset=["transaction_id"])
data[duplication].sort_values('transaction_id').head()

KeyError: 'transation_id'

In [ ]:
data.drop_duplicates(subset=[''])