In [79]:
import numpy as np
l = list()

In [80]:

l = (i for i in range(10)); l


<generator object <genexpr> at 0x0FB39098>

In [81]:
ar = np.array(l)

In [82]:
ar

array(<generator object <genexpr> at 0x0FB39098>, dtype=object)

In [83]:
ar.max()
ar.std()


AttributeError: 'generator' object has no attribute 'dtype'

In [14]:
m = np.array(([1,3],[3,4]))

In [15]:
m


array([[1, 3],
       [3, 4]])

In [21]:
b = np.linspace(0, 2, 4)

b


array([0.        , 0.66666667, 1.33333333, 2.        ])

In [22]:
b**b

array([1.        , 0.76314283, 1.46752322, 4.        ])

In [26]:
c = np.arange(24).reshape(2,3,4); c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [30]:
c.ndim ## affiche le nombre de dimensions 

3

In [62]:
ar = np.array(([1,2,3],[4,5,6], [7,8,9])) 


In [63]:
ar[1:][0:1] # ??? 1e ligne 2e colonnes

array([[4, 5, 6]])

In [64]:
ar[1,:] juste la 2eme ligne

SyntaxError: invalid syntax (<ipython-input-64-9d5134aeff05>, line 1)

In [93]:
e = np.array(([1,2],[3,4]))


In [94]:
e

array([[1, 2],
       [3, 4]])

In [95]:
e.sum(axis=0)

array([4, 6])

In [96]:
e.sum(axis=1)

array([3, 7])

In [97]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [99]:
np.tile(3, 8)


array([3, 3, 3, 3, 3, 3, 3, 3])

In [106]:
z = np.zeros((2,4)); z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [103]:
np.zeros(4)

array([0., 0., 0., 0.])

In [108]:
z.dtype

dtype('float64')