# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np

RuntimeError: The current Numpy installation ('c:\\users\\guillaume\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

#### Q2 : Afficher la version de numpy et la configuration 

In [3]:
!pip -V numpy

pip 20.2.3 from c:\users\gruel\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)



#### Q3 : Créer un vecteur nul de taille 10

In [15]:
v = np.zeros((10,10)); v

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [16]:
v[3] = 1; v

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [53]:

vecZ = np.arange(10,50)
vecZ

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [54]:
vecZ.reshape(4,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [57]:
vecZ[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [61]:
mat = np.array([[1,0,4],[2,8,6],[3,5,7]]); mat

array([[1, 0, 4],
       [2, 8, 6],
       [3, 5, 7]])

#### Q8 : Créer une matrice identié 3x3 

In [63]:
matIdentite = np.array([[0,0,1],[0,1,0],[1,0,0]]); matIdentite

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 0]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [4]:
matCube = (np.random.rand(3,3,3))*10 ; matCube

array([[[3.40851154, 9.59050309, 1.71737051],
        [6.2925653 , 0.24930453, 1.02765935],
        [7.77089787, 6.33296106, 2.29466734]],

       [[6.78177326, 5.06320331, 9.31284676],
        [8.56052538, 7.62775511, 8.22059322],
        [4.89050297, 6.14588455, 6.98809009]],

       [[7.20649022, 2.74985074, 6.3151556 ],
        [0.25560681, 1.15641347, 2.52820765],
        [1.48602973, 1.86247046, 9.44846696]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [9]:
matDix = (np.random.rand(8,8))*10 ; matDix


array([[1.76684214, 2.27777734, 7.87718392, 1.35768592, 6.91035265,
        2.87915217, 7.04419152, 7.45125488],
       [1.81888148, 6.86265742, 0.10675126, 0.21252606, 6.43245404,
        3.65509069, 9.0089657 , 9.05363068],
       [5.61620795, 9.93624927, 9.38713545, 5.27936401, 9.56106185,
        8.44057008, 4.01273465, 6.48564021],
       [7.3649085 , 6.42405843, 9.93142599, 1.10045695, 6.68053804,
        1.23964119, 6.72760578, 4.86992362],
       [0.15107294, 2.81072899, 0.41299655, 3.53014457, 2.43211763,
        7.56181711, 9.8551361 , 5.53770818],
       [1.81363947, 5.59622027, 8.04289434, 4.4879673 , 8.30810694,
        8.9081022 , 5.6642813 , 3.45531155],
       [5.97226138, 1.76149132, 0.38836506, 7.6764606 , 7.60335752,
        5.558976  , 8.183157  , 3.79239694],
       [4.79775236, 0.5665975 , 3.99397359, 5.4844867 , 8.22956352,
        1.29355116, 3.21777587, 5.89042284]])

In [10]:
matDix.min()


0.10675125831454024

In [11]:
matDix.max()

9.936249266938507

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [18]:
matCinq = (np.random.rand(5,5))*10

In [19]:
matCinq[1][0]= 1
matCinq[2][1]= 2
matCinq[3][2]= 3
matCinq[4][3]= 4; matCinq

array([[7.26828872, 9.52608659, 3.12844931, 7.65572486, 7.74028179],
       [1.        , 9.59547141, 4.44285982, 9.10927685, 1.30648675],
       [6.45996645, 2.        , 3.77614059, 8.84269417, 6.88723265],
       [6.4606045 , 7.92980588, 3.        , 5.08170935, 0.29189963],
       [7.36791974, 2.82260934, 7.77794973, 4.        , 3.79629725]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [12]:
listRandom = (np.random.rand(5))*10 ; listRandom

array([3.67524029, 9.52959591, 1.32915351, 6.64612328, 9.52645758])

In [14]:
listRandom.sum()

30.706570579105865

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [24]:
listRandom = (np.random.rand(5))*10
moyenne = 0
for i, element in enumerate(listRandom) : 
    moyenne += element
moyenne = moyenne % i
moyenne

1.9209851059647143

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [63]:
def taille(listt : list):
    for i, element in enumerate(listt) :
        element += element
    return i+1 

In [64]:
l = [x for x in range(10)]
print(l)
print(taille(l))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
10


#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [66]:
listRandom = (np.random.rand(10))
listRandom

array([0.22898231, 0.80830735, 0.59327346, 0.77695545, 0.99539393,
       0.50964037, 0.44918349, 0.64439305, 0.60497582, 0.91977343])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [4]:
a = [x for x in range(5)] 
b = [x for x in range(5)]

if a == b :
    print(True)
else:
    print(False)

True


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [14]:
a = np.ones(10, dtype=np.float32);a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [18]:
a.dtype=np.int32
a.dtype

dtype('int32')

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [28]:
b = (np.random.rand(5,5))*10;  b


array([[6.38261801, 3.87637867, 6.43851621, 8.82765154, 8.52527953],
       [2.86408436, 7.91539594, 5.10239582, 3.42069047, 8.67668157],
       [7.71898712, 0.05761357, 0.62443126, 8.19175206, 9.8185045 ],
       [0.25990752, 8.92963477, 2.06034994, 6.71825427, 0.10911835],
       [5.50431997, 8.74970848, 0.45989662, 6.16730793, 0.24242698]])

In [29]:
for x in range(b.shape[0]):
    b = b / np.linalg.norm(b, axis=1, keepdims=True)
    
b

array([[0.40543855, 0.24623647, 0.40898933, 0.56075269, 0.54154532],
       [0.2112138 , 0.58372612, 0.37627956, 0.25226109, 0.63986763],
       [0.51634178, 0.00385391, 0.04176972, 0.54796617, 0.65678359],
       [0.02286606, 0.78560838, 0.18126477, 0.5910563 , 0.00959998],
       [0.45685549, 0.72622092, 0.03817116, 0.51188312, 0.0201213 ]])

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [30]:
matRand = (np.random.rand(2,2))*10; matRand

array([[0.63703758, 0.93583906],
       [0.4457831 , 0.70878946]])

In [32]:
matRand.transpose()

array([[0.63703758, 0.4457831 ],
       [0.93583906, 0.70878946]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [53]:
def functionRand(limite : int) -> int :
    nb = 99
    while nb > limite : 
        nb = int((np.random.rand(1))*10)
    return nb

In [54]:
matRand = (np.random.rand(6,6)); matRand

array([[0.46680052, 0.6977216 , 0.75573574, 0.17870472, 0.90614305,
        0.43154029],
       [0.30217471, 0.941769  , 0.76551801, 0.48380114, 0.23225059,
        0.82672349],
       [0.40133058, 0.9720369 , 0.86572733, 0.44874701, 0.04344584,
        0.96520669],
       [0.09988974, 0.94936146, 0.09113888, 0.81487977, 0.39575581,
        0.77808278],
       [0.26534474, 0.53829416, 0.68566921, 0.26149602, 0.56015428,
        0.05667002],
       [0.28096851, 0.10943499, 0.12149917, 0.39774909, 0.64088431,
        0.8347498 ]])

In [57]:


nbRand = functionRand(10)
matRand[functionRand(6)][functionRand(6)] = nbRand
matRand
      

array([[0.46680052, 0.6977216 , 0.75573574, 0.17870472, 0.90614305,
        0.43154029],
       [0.30217471, 0.941769  , 0.76551801, 0.48380114, 0.23225059,
        0.82672349],
       [6.        , 0.9720369 , 0.86572733, 0.44874701, 0.04344584,
        0.96520669],
       [9.        , 0.94936146, 0.09113888, 0.81487977, 0.39575581,
        0.77808278],
       [0.26534474, 0.53829416, 0.68566921, 0.26149602, 0.56015428,
        0.05667002],
       [0.28096851, 0.10943499, 0.12149917, 2.        , 0.64088431,
        0.8347498 ]])

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [69]:
matCube5x5x3 = (np.random.rand(3,5,5))
matRand5x5 = (np.random.rand(5,5))

In [70]:
matCube5x5x3

array([[[0.95929648, 0.93368125, 0.80976248, 0.60633774, 0.50759693],
        [0.01551462, 0.12602408, 0.73507893, 0.9822    , 0.26824491],
        [0.32121837, 0.43216274, 0.07234611, 0.62716346, 0.55487707],
        [0.5682744 , 0.54029935, 0.97048849, 0.61468864, 0.9646999 ],
        [0.54511468, 0.51233073, 0.03806295, 0.7466305 , 0.48205034]],

       [[0.00881641, 0.8648661 , 0.13118148, 0.24330117, 0.05704851],
        [0.91996351, 0.5740632 , 0.16553712, 0.34053378, 0.31049377],
        [0.10958143, 0.86115209, 0.23637435, 0.96627016, 0.821065  ],
        [0.87577058, 0.2917522 , 0.7818954 , 0.70412845, 0.23387219],
        [0.92270426, 0.43051989, 0.59496076, 0.075557  , 0.60698931]],

       [[0.60656829, 0.33751804, 0.75630173, 0.30964948, 0.53725705],
        [0.2080426 , 0.86932019, 0.75268168, 0.13786732, 0.59820138],
        [0.75630662, 0.59808967, 0.19769891, 0.84658667, 0.59028029],
        [0.08015992, 0.66577643, 0.68138778, 0.03683779, 0.24884001],
        [0.00597

In [71]:
for i in range(0,3,1): 
    matCube5x5x3[i] = matCube5x5x3[i] @ matRand5x5
matCube5x5x3    

array([[[1.80693967, 1.51122772, 1.91482366, 1.26429798, 1.93337244],
        [1.1785796 , 0.76849404, 0.85811437, 0.5685259 , 1.09836642],
        [1.01542464, 0.75760581, 0.93665396, 0.71045841, 1.09021448],
        [1.85256892, 1.17066473, 1.94085726, 1.29790077, 1.90852209],
        [1.17549478, 1.03428512, 1.04931155, 0.79548479, 1.28372731]],

       [[0.42795173, 0.26287145, 0.55575694, 0.36797278, 0.45777223],
        [1.10949761, 1.15384112, 1.16830516, 0.81859972, 1.27042765],
        [1.42823035, 0.8509963 , 1.35778265, 1.0099821 , 1.48126219],
        [1.52644715, 1.41527745, 1.37846491, 0.89832569, 1.5895692 ],
        [1.29840252, 1.07447567, 1.52183233, 1.00473638, 1.43698507]],

       [[1.29122018, 0.94212129, 1.38202531, 0.89678009, 1.34907471],
        [1.09364808, 0.52214995, 1.40599633, 0.89450335, 1.12893097],
        [1.51706585, 1.33193626, 1.39754816, 1.02577279, 1.64947552],
        [0.68350132, 0.29382198, 0.92689595, 0.5465309 , 0.67894661],
        [0.69594